
name: Complex Workflow Challenge

on: [push]

jobs:

  Ubuntu-job:

    name:  Ubuntu job
    runs-on:  ubuntu-latest
    steps:
    - name: Ubuntu date
      run: date

  Windows-job:

    name:  Windows job
    runs-on:  windows-latest
    steps:
    - name: Windows date
      run: date

  MacOS-job:

    name:  MacOS job
    runs-on:  macos-latest
    steps:
    - name: MacOS date
      run: date

  depends-job:

    name:  Depends job
    runs-on:  ubuntu-latest
    needs: [ Ubuntu-job, Windows-job, MacOS-job ]
    steps:
    - name: Depends date
      run: date
